name: Windows Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
  OPENCV_INCLUDE_PATHS: "+C:\\tools\\opencv\\build\\include"
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # - name: Install llvm via choco
      #   run: choco install llvm

      - name: Install opencv via choco
        run: choco install opencv

      - name: Find OpenCV library and set environment variables
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path "C:\tools\opencv" -Recurse -Filter "opencv_world*.lib" |
            Where-Object { $_.Name -notmatch "d\.lib$" }

          if ($files.Count -eq 0) {
              Write-Error "No matching OpenCV release libraries found (excluding debug builds)."
              exit 1
          }

          $libFile = $files | Sort-Object Name -Descending | Select-Object -First 1

          $libName = [System.IO.Path]::GetFileNameWithoutExtension($libFile.Name)
          $libPath = $libFile.DirectoryName

          echo "Found library: $libName in $libPath"

          echo "OPENCV_LINK_LIBS=$libName" >> $env:GITHUB_ENV
          echo "OPENCV_LINK_PATHS=+$libPath" >> $env:GITHUB_ENV
      - name: Tree C:\tools\opencv
        shell: pwsh
        run: tree C:\tools\opencv /F

      - name: Build the project
        run: cargo build --release

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: target/release/opencv_example.exe
